### ISSUE TITLE
ScalecubeServiceDiscovery consume ServiceEndpoint with all null-value fields

### ISSUE THREAD

**Issue by eutkin** [scalecube/scalecube-services#640]
[stacktrace](https://pastebin.com/a62dKDNQ). Cause - discovery consume discovery event, where serviceEndpoint have null value fields.

I have two service, store and redirect. 

Configuration Store service: 
```yml
spring:
  scalecube:
    discovery:
      transport:
        port: 9000
```

This is equivalent on scalecube:
```java
new ScalecubeServiceDiscovery(endpoint)
    .options(config -> config.transport(tc -> tc.port(9000));
```

Configuration Redirect service:
```yml
spring:
  scalecube:
    discovery:
      membership:
        seed-members: localhost:9000
```

This is equivalent on scalecube:
```java
new ScalecubeServiceDiscovery(endpoint)
    .options(config -> config
        .membership(mc -> mc.seedMembers(Address.from("localhost:9000"))
));
```

I used follow projects: 

* [scalecube spring boot starer](https://github.com/scalecube/spring-boot-scalecube-starter/tree/feature/add-autoconfigure)
* [example project](https://github.com/eutkin/Spiderweb)

I will create demo project of vanilla scalecube and show his later
